Setup project
koomekevo/forexworld pull request #2
Opened 2022-02-01 09:56 UTC by koomekevo

This pull request has been created by the setup-project branch to achieve the following:

- Add dependencies such as prop-types, redux, redux-logger, and redux-thunk.
- Add devDependencies such as Eslint and Stylelint

2022-02-03 11:41 UTC, Mihndim2020 requested changes
### Hi @koomekevo, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages,
:heavy_check_mark: Descriptive Readme file,
:heavy_check_mark: Your app is running free of `Linter` errors.

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)


# Status: Requires Changes ♻️
_Check the comments below and under the review._

- [ ] Great video presentation, but as it is a requirement for this project, please  it will be nice to highlight;
- all your project features,
- a piece of the code that you find interesting or are proud of making.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 11:41 UTC, Mihndim2020 commented on src/__tests__/__snapshots__/snapshots.test.js
> +//   const getState = () => ({ price: 0.145947, ticket: 'EUR/USD' });
- [ ] Please kindly remove `commented code` from your `code base`, as it make your `code base` dirty and less readable.

2022-02-03 11:41 UTC, Mihndim2020 commented on src/components/Stocks.js
> +        </button>
- [ ] As it is requirement for this project, which also improves the user experience of your app, kindly ensure  there's a link(`"Back" button`) in the `Detail page` that you can click on to go to the `Home page`. This button is absent in your app, please kindly fix that. See screenshot of the requirements below;

![backbutton](https://user-images.githubusercontent.com/65852621/152334021-f32e00b9-6377-448a-87f3-e1aa6b61a3e4.png)

2022-02-03 11:41 UTC, Mihndim2020 commented on src/components/Majors.js
> +        </button>
- [ ] As it is requirement for this project, which also improves the user experience of your app, kindly ensure  there's a link(`"Back" button`) in the `Detail page` that you can click on to go to the `Home page`. This button is absent in your app, please kindly fix that. See screenshot of the requirements below;

![backbutton](https://user-images.githubusercontent.com/65852621/152334021-f32e00b9-6377-448a-87f3-e1aa6b61a3e4.png)

2022-02-03 11:41 UTC, Mihndim2020 commented on src/components/Forex.js
> +        </button>
- [ ] As it is requirement for this project, which also improves the user experience of your app, kindly ensure  there's a link(`"Back" button`) in the `Detail page` that you can click on to go to the `Home page`. This button is absent in your app, please kindly fix that. See screenshot of the requirements below;

![backbutton](https://user-images.githubusercontent.com/65852621/152334021-f32e00b9-6377-448a-87f3-e1aa6b61a3e4.png)

2022-02-03 11:41 UTC, Mihndim2020 commented on src/components/EFTs.js
> +        </button>
- [ ] As it is requirement for this project, which also improves the user experience of your app, kindly ensure  there's a link(`"Back" button`) in the `Detail page` that you can click on to go to the `Home page`. This button is absent in your app, please kindly fix that. See screenshot of the requirements below;

![backbutton](https://user-images.githubusercontent.com/65852621/152334021-f32e00b9-6377-448a-87f3-e1aa6b61a3e4.png)

2022-02-04 14:30 UTC, Emmyn5600 approved these changes
STATUS: APPROVED :partying_face: 

Wooow👏, Your project is complete!  There is nothing else to say other than... it's time to merge it. 👏

Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-02-04 15:45 UTC, merged